---
title: "simpimp paper figs & ana"
author: "Erica Yoon"
date: "February 22, 2016"
output: html_document
---

```{r global_options, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(fig.width=6, fig.height=5, fig.crop = F, fig.path='figs/',
                      echo=FALSE, warning=FALSE, cache=T, message=FALSE, sanitize = T)
```

```{r libraries, cache=FALSE, include=FALSE}
rm(list = ls())
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(lme4)
library(langcog)
library(psych)
library(stringr)
theme_set(theme_bw())
# setwd("Documents/Research/simpimp_GIT/paper/cronbach")
```

```{r data, message=FALSE, include=FALSE}
d_et <- fread("../simpimp_et_acc.csv", data.table=FALSE)
et_rts <- fread("../simpimp_et_rt.csv", data.table=FALSE)
d_ip <- fread("../simpimp_ip.csv", data.table=FALSE)
```

```{r psych_alpha_fn}
# redo psych::alpha

alpha_nopca <- function (x, keys = NULL, cumulative = FALSE, 
                         title = NULL, max = 10, 
    na.rm = TRUE, check.keys = FALSE, n.iter = 1, delete = TRUE, 
    use = "pairwise") 
{
  
    alpha.1 <- function(C, R) {
        n <- dim(C)[2]
        alpha.raw <- (1 - tr(C)/sum(C)) * (n/(n - 1))
        alpha.std <- (1 - n/sum(R)) * (n/(n - 1))
        smc.R <- smc(R)
        G6 <- (1 - (n - sum(smc.R))/sum(R))
        av.r <- (sum(R) - n)/(n * (n - 1))
        sn <- n * av.r/(1 - av.r)
        Q = (2 * n^2/((n - 1)^2 * (sum(C)^3))) * (sum(C) * (tr(C^2) + 
            (tr(C))^2) - 2 * (tr(C) * sum(C^2)))
        result <- list(raw = alpha.raw, std = alpha.std, G6 = G6, 
            av.r = av.r, sn = sn, Q = Q)
        return(result)
    }
    
    cl <- match.call()
    if (!is.matrix(x) && !is.data.frame(x)) 
        stop("Data must either be a data frame or a matrix")
    nvar <- dim(x)[2]
    nsub <- dim(x)[1]
    scores <- NULL
    response.freq <- NULL
    if (nsub != nvar) {
        item.var <- apply(x, 2, sd, na.rm = na.rm)
        bad <- which((item.var <= 0) | is.na(item.var))
        if ((length(bad) > 0) && delete) {
            for (baddy in 1:length(bad)) {
                warning("Item = ", colnames(x)[bad][baddy], " had no variance and was deleted")
            }
            x <- x[, -bad]
            nvar <- nvar - length(bad)
        }
        response.freq <- response.frequencies(x, max = max)
        C <- cov(x, use = use)
    }
    else {
        C <- x
    }
    
    if (is.null(keys)) {
        keys <- rep(1, nvar)
    }
    else {
        keys <- as.vector(keys)
        if (length(keys) < nvar) {
            temp <- keys
            keys <- rep(1, nvar)
            names(keys) <- colnames(x)
            keys[temp] <- -1
        }
    }
    key.d <- diag(keys)
    C <- key.d %*% C %*% key.d
    signkey <- strtrim(keys, 1)
    signkey[signkey == "1"] <- ""
    colnames(x) <- paste(colnames(x), signkey, sep = "")
    if (nsub != nvar) {
        if (any(keys < 0)) {
            min.item <- min(x, na.rm = na.rm)
            max.item <- max(x, na.rm = na.rm)
            adjust <- max.item + min.item
            flip.these <- which(keys < 0)
            x[, flip.these] <- adjust - x[, flip.these]
        }
        if (cumulative) {
            total <- rowSums(x, na.rm = na.rm)
        }
        else {
            total <- rowMeans(x, na.rm = na.rm)
        }
        mean.t <- mean(total, na.rm = na.rm)
        sdev <- sd(total, na.rm = na.rm)
        raw.r <- cor(total, x, use = use)
        t.valid <- colSums(!is.na(x))
    }
    else {
        total <- NULL
        totals <- TRUE
    }
    R <- cov2cor(C)
    drop.item <- vector("list", nvar)
    alpha.total <- alpha.1(C, R)
    if (nvar > 2) {
        for (i in 1:nvar) {
            drop.item[[i]] <- alpha.1(C[-i, -i, drop = FALSE], 
                R[-i, -i, drop = FALSE])
        }
    }
    else {
        drop.item[[1]] <- drop.item[[2]] <- c(rep(R[1, 2], 2), 
            smc(R)[1], R[1, 2], NA, NA)
    }
    by.item <- data.frame(matrix(unlist(drop.item), ncol = 6, 
        byrow = TRUE))
    if (nsub > nvar) {
        by.item[6] <- sqrt(by.item[6]/nsub)
        colnames(by.item) <- c("raw_alpha", "std.alpha", "G6(smc)", 
            "average_r", "S/N", "alpha se")
    }
    else {
        by.item <- by.item[-6]
        colnames(by.item) <- c("raw_alpha", "std.alpha", "G6(smc)", 
            "average_r", "S/N")
    }
    rownames(by.item) <- colnames(x)
    Vt <- sum(R)
    item.r <- colSums(R)/sqrt(Vt)
    RC <- R
    diag(RC) <- smc(R)
    Vtc <- sum(RC)
    item.rc <- colSums(RC)/sqrt(Vtc)
    if (nvar > 1) {
        r.drop <- rep(0, nvar)
        for (i in 1:nvar) {
            v.drop <- sum(C[-i, -i, drop = FALSE])
            c.drop <- sum(C[, i]) - C[i, i]
            r.drop[i] <- c.drop/sqrt(C[i, i] * v.drop)
        }
    }
    item.means <- colMeans(x, na.rm = na.rm)
    item.sd <- apply(x, 2, sd, na.rm = na.rm)
    if (nsub > nvar) {
        ase = sqrt(alpha.total$Q/nsub)
        alpha.total <- data.frame(alpha.total[1:5], ase = ase, 
            mean = mean.t, sd = sdev)
        colnames(alpha.total) <- c("raw_alpha", "std.alpha", 
            "G6(smc)", "average_r", "S/N", "ase", "mean", "sd")
        rownames(alpha.total) <- ""
        stats <- data.frame(n = t.valid, raw.r = t(raw.r), std.r = item.r, 
            r.cor = item.rc, r.drop = r.drop, mean = item.means, 
            sd = item.sd)
    }
    else {
        alpha.total <- data.frame(alpha.total[-6])
        colnames(alpha.total) <- c("raw_alpha", "std.alpha", 
            "G6(smc)", "average_r", "S/N")
        rownames(alpha.total) <- ""
        stats <- data.frame(r = item.r, r.cor = item.rc, r.drop = r.drop)
    }
    rownames(stats) <- colnames(x)
    if (n.iter > 1) {
        if (nsub == nvar) {
            message("bootstrapped confidence intervals require raw data")
            boot <- NULL
            boot.ci <- NULL
        }
        else {
            boot <- vector("list", n.iter)
            boot <- mclapply(1:n.iter, function(XX) {
                xi <- x[sample.int(nsub, replace = TRUE), ]
                C <- cov(xi, use = "pairwise")
                if (!is.null(keys)) {
                  key.d <- diag(keys)
                  xi <- key.d %*% C %*% key.d
                }
                R <- cov2cor(C)
                alpha.1(C, R)
            })
            boot <- matrix(unlist(boot), ncol = 6, byrow = TRUE)
            colnames(boot) <- c("raw_alpha", "std.alpha", "G6(smc)", 
                "average_r", "s/n", "ase")
            boot.ci <- quantile(boot[, 1], c(0.025, 0.5, 0.975))
        }
    }
    else {
        boot = NULL
        boot.ci <- NULL
    }
    result <- list(total = alpha.total, alpha.drop = by.item, 
        item.stats = stats, response.freq = response.freq, keys = keys, 
        scores = total, nvar = nvar, boot.ci = boot.ci, boot = boot, 
        call = cl, title = title)
    class(result) <- c("psych", "alpha")
    return(result)
}
```

```{r cronbach_alpha}
get.frame <- function(x) {
  x <- as.data.frame(x)
  non.null.cols <- apply(x, 2, function(x) {!all(is.na(x))})
  x <- x[, non.null.cols]
  return(x)
}

# eye-tracking accuracy alpha
et.acc.alphas <- d_et %>%
  filter(age_group!="adult") %>%
  filter(t.crit >.78 & t.crit < 3) %>%
  filter(trial_type != "inference") %>%
  mutate(trial_num = as.numeric(as.character(trial_num))) %>%
  group_by(subid, age_group, trial_num) %>%
  summarise(correct = mean(correct)) %>%
  select(subid, age_group, trial_num, correct) %>%
  group_by(age_group, subid) %>%
  arrange(subid, trial_num) %>%
  mutate(trial_order = str_c("t",as.character(1:length(trial_num))), 
         n = length(trial_num)) %>%
  select(-trial_num) %>%
  spread(trial_order, correct) %>%
  group_by(age_group, add=FALSE) %>%
  summarise(n = mean(n), 
            raw.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, t4, t5, t6, 
                                              t7, t8, t9, t10, t11, t12
                                              # t13, t14, t15, t16 
                                              )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$raw_alpha, 
            std.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, t4, t5, t6,
                                                    t7, t8, t9, t10, t11, t12
                                              # t13, t14, t15, t16
                                                    )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$std.alpha)

# eye-tracking rt alpha
et_rt_ms <- et_rts %>%
  filter(age_group != "adult") %>%
  filter(trial_type != "inference") %>%
  group_by(trial_num, age_group, subid) %>%
  summarise(rt = mean(rt)) %>%
  ungroup()

et.rt.alphas <- et_rt_ms %>%
  mutate(trial_num = as.numeric(as.character(trial_num))) %>%
  group_by(subid, age_group, trial_num) %>% 
  summarise(rt = mean(rt)) %>%
  select(subid, age_group, trial_num, rt) %>%
  group_by(age_group, subid) %>%
  arrange(subid, trial_num) %>%
  mutate(trial_order = str_c("t",as.character(1:length(trial_num))), 
         n = length(trial_num)) %>%
  select(-trial_num) %>%
  spread(trial_order, rt) %>%
  group_by(age_group, add=FALSE) %>%
  summarise(n = mean(n), 
            raw.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, 
                                                    t4, t5, t6, 
                                              t7, t8, t9
                                              # , t10, t11, t12
                                              )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$raw_alpha, 
            std.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, 
                                                    t4, t5, t6, 
                                                    t7, t8, t9
                                                    # , t10, t11, t12
                                                    )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$std.alpha)

# tablet accuracy alpha
ip.acc.alphas <- d_ip %>%
  filter(trial_type != "inference") %>%
  mutate(trial_num = as.numeric(as.character(trial_num)) - 2) %>%
  select(subid, age_group, trial_num, correct) %>%
  group_by(age_group, subid) %>%
  arrange(subid, trial_num) %>%
  mutate(trial_order = str_c("t",as.character(1:length(trial_num))), 
         n = length(trial_num)) %>%
  select(-trial_num) %>%
  spread(trial_order, correct) %>%
  group_by(age_group, add=FALSE) %>%
  summarise(n = mean(n), 
            raw.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, t4, t5, t6, 
                                              t7, t8, t9, t10, t11, t12
                                              # t13, t14, t15, t16
                                              )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$raw_alpha, 
            std.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, t4, t5, t6, 
                                                    t7, t8, t9, t10, t11, t12
                                                    # t13, t14, t15, t16
                                                    )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$std.alpha)


# tablet rt alpha
ip.rt.alphas <- d_ip %>%
  filter(trial_type != "inference") %>%
  mutate(trial_num = as.numeric(as.character(trial_num))) %>%
  group_by(subid, age_group, trial_num) %>%
  summarise(rt = mean(rt, na.rm = TRUE)) %>%
  select(subid, age_group, trial_num, rt) %>%
  group_by(age_group, subid) %>%
  arrange(subid, trial_num) %>%
  mutate(trial_order = str_c("t",as.character(1:length(trial_num))), 
         n = length(trial_num)) %>%
  select(-trial_num) %>%
  spread(trial_order, rt) %>%
  group_by(age_group, add=FALSE) %>%
  summarise(n = mean(n), 
            raw.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, t4, t5, t6, 
                                              t7, t8, t9, t10, t11, t12
                                              # t13, t14, t15, t16
                                              )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$raw_alpha, 
            std.alpha = alpha_nopca(get.frame(cbind(t1, t2, t3, t4, t5, t6, 
                                                    t7, t8, t9, t10, t11, t12
                                                    # t13, t14, t15, t16
                                                    )), 
                              na.rm=TRUE, delete=TRUE, 
                              check.keys=FALSE)$total$std.alpha)
et.acc.alphas
et.rt.alphas
ip.acc.alphas
ip.rt.alphas
```
